/* This file was generated by Unframer, do not edit manually */
import * as React from "react"

import { UnframerBreakpoint } from "unframer"

type Locale = string
export interface Props {
    children?: React.ReactNode
    locale?: Locale
    style?: React.CSSProperties
    className?: string
    id?: string
    width?: any
    height?: any
    layoutId?: string
    "variant"?: 'Desktop' | 'Tablet' | 'Phone'
    "icon1"?: {src: string, srcSet?: string, alt?: string}
    "name1"?: string
    "designation1"?: string
    "email1"?: string
    "telLink1"?: string
    "phone1"?: string
    "emailLink1"?: string
    "image2"?: {src: string, srcSet?: string, alt?: string}
    "name2"?: string
    "designation2"?: string
    "email2"?: string
    "telLink2"?: string
    "phone2"?: string
    "emailLink2"?: string
    "text"?: string
    "image3"?: {src: string, srcSet?: string, alt?: string}
    "title3"?: string
    "designation3"?: string
    "email3"?: string
    "telLink3"?: string
    "phone3"?: string
    "emailLink3"?: string
}

const ContactBodyFramerComponent = (props: Props) => any

type VariantsMap = Partial<Record<UnframerBreakpoint, Props['variant']>> & { base: Props['variant'] }

ContactBodyFramerComponent.Responsive = (props: Omit<Props, 'variant'> & {variants?: VariantsMap}) => any

export default ContactBodyFramerComponent

