/* This file was generated by Unframer, do not edit manually */
import * as React from "react"

import { UnframerBreakpoint } from "unframer"

type Locale = string
export interface Props {
    children?: React.ReactNode
    locale?: Locale
    style?: React.CSSProperties
    className?: string
    id?: string
    width?: any
    height?: any
    layoutId?: string
    "variant"?: 'Desktop' | 'Tablet' | 'Phone'
    "tag"?: string
    "title"?: string
    "subheading"?: string
    "image1"?: {src: string, srcSet?: string, alt?: string}
    "image2"?: {src: string, srcSet?: string, alt?: string}
    "image3"?: {src: string, srcSet?: string, alt?: string}
    "image4"?: {src: string, srcSet?: string, alt?: string}
    "paragraph"?: undefined
}

const CosaMissionFramerComponent = (props: Props) => any

type VariantsMap = Partial<Record<UnframerBreakpoint, Props['variant']>> & { base: Props['variant'] }

CosaMissionFramerComponent.Responsive = (props: Omit<Props, 'variant'> & {variants?: VariantsMap}) => any

export default CosaMissionFramerComponent

