/* This file was generated by Unframer, do not edit manually */
import * as React from "react"

import { UnframerBreakpoint } from "unframer"

type Locale = string
export interface Props {
    children?: React.ReactNode
    locale?: Locale
    style?: React.CSSProperties
    className?: string
    id?: string
    width?: any
    height?: any
    layoutId?: string
    "variant"?: 'Desktop' | 'Tablet' | 'Phone'
    "tag"?: string
    "title"?: string
    "section1Tag"?: string
    "section1Subtag"?: string
    "section1Title"?: string
    "section1Paragraph"?: undefined
    "section2Tag"?: string
    "section2Subtag"?: string
    "section2Title"?: string
    "section2Paragraph"?: undefined
    "section3Tag"?: string
    "section3Subtag"?: string
    "section3Title"?: string
    "text"?: undefined
}

const CosaStepsFramerComponent = (props: Props) => any

type VariantsMap = Partial<Record<UnframerBreakpoint, Props['variant']>> & { base: Props['variant'] }

CosaStepsFramerComponent.Responsive = (props: Omit<Props, 'variant'> & {variants?: VariantsMap}) => any

export default CosaStepsFramerComponent

