/* This file was generated by Unframer, do not edit manually */
import * as React from "react"

import { UnframerBreakpoint } from "unframer"

type Locale = string
export interface Props {
    children?: React.ReactNode
    locale?: Locale
    style?: React.CSSProperties
    className?: string
    id?: string
    width?: any
    height?: any
    layoutId?: string
    "variant"?: 'Desktop' | 'Tablet' | 'Phone'
    "image"?: {src: string, srcSet?: string, alt?: string}
    "title"?: string
    "point1"?: string
    "icon1"?: {src: string, srcSet?: string, alt?: string}
    "paragraph1"?: string
    "point2"?: string
    "icon2"?: {src: string, srcSet?: string, alt?: string}
    "paragraph2"?: string
    "point3"?: string
    "icon3"?: {src: string, srcSet?: string, alt?: string}
    "paragraph3"?: string
    "point4"?: string
    "icon4"?: {src: string, srcSet?: string, alt?: string}
    "paragraph4"?: string
    "point5"?: string
    "icon5"?: {src: string, srcSet?: string, alt?: string}
    "paragraph5"?: string
    "point6"?: string
    "paragraph6"?: string
    "icon6"?: {src: string, srcSet?: string, alt?: string}
    "icon7"?: {src: string, srcSet?: string, alt?: string}
    "point7"?: string
    "paragraph7"?: string
}

const DashboardFramerComponent = (props: Props) => any

type VariantsMap = Partial<Record<UnframerBreakpoint, Props['variant']>> & { base: Props['variant'] }

DashboardFramerComponent.Responsive = (props: Omit<Props, 'variant'> & {variants?: VariantsMap}) => any

export default DashboardFramerComponent

