/* This file was generated by Unframer, do not edit manually */
import * as React from "react"

import { UnframerBreakpoint } from "unframer"

type Locale = string
export interface Props {
    children?: React.ReactNode
    locale?: Locale
    style?: React.CSSProperties
    className?: string
    id?: string
    width?: any
    height?: any
    layoutId?: string
    "variant"?: 'Desktop' | 'Tablet' | 'Phone'
    "tag"?: string
    "title"?: string
    "hospitalTitle1"?: string
    "hospitalLogo1"?: {src: string, srcSet?: string, alt?: string}
    "hospitalTitle2"?: string
    "hospitalLogo2"?: {src: string, srcSet?: string, alt?: string}
    "hospitalParagraph2"?: string
    "hospitalParagraph1"?: string
}

const ExploreFramerComponent = (props: Props) => any

type VariantsMap = Partial<Record<UnframerBreakpoint, Props['variant']>> & { base: Props['variant'] }

ExploreFramerComponent.Responsive = (props: Omit<Props, 'variant'> & {variants?: VariantsMap}) => any

export default ExploreFramerComponent

