/* This file was generated by Unframer, do not edit manually */
import * as React from "react"

import { UnframerBreakpoint } from "unframer"

type Locale = string
export interface Props {
    children?: React.ReactNode
    locale?: Locale
    style?: React.CSSProperties
    className?: string
    id?: string
    width?: any
    height?: any
    layoutId?: string
    "variant"?: 'Desktop' | 'Tablet' | 'Phone'
    "linkedInLink"?: string
    "email"?: string
    "phone"?: string
    "homeLink"?: string
    "teamLink"?: string
    "cosaLink"?: string
    "lavoraLink"?: string
    "gdprLink"?: string
    "confidentialLink"?: string
    "certificateLink"?: string
    "contactLink"?: string
    "formazioneLink"?: string
    "footerText1"?: string
    "footerText2"?: string
    "slogan"?: string
}

const FooterFramerComponent = (props: Props) => any

type VariantsMap = Partial<Record<UnframerBreakpoint, Props['variant']>> & { base: Props['variant'] }

FooterFramerComponent.Responsive = (props: Omit<Props, 'variant'> & {variants?: VariantsMap}) => any

export default FooterFramerComponent

