/* This file was generated by Unframer, do not edit manually */
import * as React from "react"

import { UnframerBreakpoint } from "unframer"

type Locale = string
export interface Props {
    children?: React.ReactNode
    locale?: Locale
    style?: React.CSSProperties
    className?: string
    id?: string
    width?: any
    height?: any
    layoutId?: string
    "variant"?: 'Desktop' | 'Tablet' | 'Phone'
    "label01"?: string
    "label02"?: string
    "label03"?: string
    "label04"?: string
    "gDPRTitle"?: string
    "gDPRLi1"?: string
    "gDPRLi2"?: string
    "gDPRLi3"?: string
    "gDPRLi4"?: string
    "gDPRLi5"?: string
    "gDPRLi6"?: string
    "confidentialTitle"?: string
    "certificateTitle"?: string
    "certificateImage"?: {src: string, srcSet?: string, alt?: string}
    "formazioneTitle"?: string
    "box4Li1"?: string
    "box4Li2"?: string
    "box4Li3"?: string
    "box4Li4"?: string
    "box4Li5"?: string
    "gDPRParagraph"?: undefined
    "confidentialParagraph"?: undefined
    "certificateParagraph"?: undefined
    "formazioneParagraph"?: undefined
}

const PrivacyFramerComponent = (props: Props) => any

type VariantsMap = Partial<Record<UnframerBreakpoint, Props['variant']>> & { base: Props['variant'] }

PrivacyFramerComponent.Responsive = (props: Omit<Props, 'variant'> & {variants?: VariantsMap}) => any

export default PrivacyFramerComponent

