/* This file was generated by Unframer, do not edit manually */
import * as React from "react"

import { UnframerBreakpoint } from "unframer"

type Locale = string
export interface Props {
    children?: React.ReactNode
    locale?: Locale
    style?: React.CSSProperties
    className?: string
    id?: string
    width?: any
    height?: any
    layoutId?: string
    "variant"?: 'Desktop' | 'Tablet' | 'Phone'
    "tag"?: string
    "title"?: string
    "subheading"?: string
    "box1Title"?: string
    "box1Paragraph"?: string
    "box1Li1"?: string
    "box1Li2"?: string
    "box1Li3"?: string
    "box1Li4"?: string
    "box1Li5"?: string
    "box1LastLine"?: string
    "box1Sidetext"?: string
    "box2Title"?: string
    "box2Paragraph"?: string
    "box2Li1"?: string
    "box2Li2"?: string
    "box2Li3"?: string
    "box2Li4"?: string
    "box2Li5"?: string
    "box2Sidetag"?: string
    "box3Title"?: string
    "box3Paragraph"?: string
    "box3Li1"?: string
    "box3Li2"?: string
    "box3Li3"?: string
    "box3Li4"?: string
    "box4Li5"?: string
    "box3Sidetag"?: string
}

const TheProblemWeSolvedFramerComponent = (props: Props) => any

type VariantsMap = Partial<Record<UnframerBreakpoint, Props['variant']>> & { base: Props['variant'] }

TheProblemWeSolvedFramerComponent.Responsive = (props: Omit<Props, 'variant'> & {variants?: VariantsMap}) => any

export default TheProblemWeSolvedFramerComponent

