/* This file was generated by Unframer, do not edit manually */
import * as React from "react"

import { UnframerBreakpoint } from "unframer"

type Locale = string
export interface Props {
    children?: React.ReactNode
    locale?: Locale
    style?: React.CSSProperties
    className?: string
    id?: string
    width?: any
    height?: any
    layoutId?: string
    "variant"?: 'Desktop' | 'Tablet' | 'Phone'
    "videoLink"?: string
    "title"?: string
    "tag"?: string
    "subheading"?: string
    "body"?: string
    "li1"?: string
    "li2"?: string
    "li3"?: string
    "li4"?: string
    "li5"?: string
    "li6"?: string
    "li7"?: string
}

const ThePlatformFramerComponent = (props: Props) => any

type VariantsMap = Partial<Record<UnframerBreakpoint, Props['variant']>> & { base: Props['variant'] }

ThePlatformFramerComponent.Responsive = (props: Omit<Props, 'variant'> & {variants?: VariantsMap}) => any

export default ThePlatformFramerComponent

